// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solution.Core.Infrastructure;

#nullable disable

namespace Solution.Core.Infrastructure.Migrations
{
    [DbContext(typeof(NpgSqlContext))]
    partial class NpgSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Common.Dictionary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("描述");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("键");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("类型  0-创建类型");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("值");

                    b.HasKey("Id");

                    b.ToTable("T_Dictionary", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Common.OperationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("接口地址");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<long>("EmpId")
                        .HasColumnType("bigint")
                        .HasComment("员工id");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("员工姓名");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("操作项目的名称");

                    b.Property<string>("RequestMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("请求参数");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("响应参数");

                    b.HasKey("Id");

                    b.ToTable("T_OperationLog", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Common.ShiftInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan>("BeginTime")
                        .HasColumnType("time")
                        .HasComment("开始时间");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasComment("结束时间");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("班次名称");

                    b.HasKey("Id");

                    b.ToTable("T_ShiftInfo", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Common.UserInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("地址");

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("联系方式");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("用户名称");

                    b.HasKey("Id");

                    b.ToTable("T_UserInfo", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Common.VersionApp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("数据库版本");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasComment("更新时间");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<int?>("IsUpdate")
                        .HasColumnType("int")
                        .HasComment("是否需要强制更新 0：不需要 1：需要");

                    b.Property<int?>("Source")
                        .HasColumnType("int")
                        .HasComment("类型 1:app");

                    b.Property<string>("Version")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("app版本号");

                    b.HasKey("Id");

                    b.ToTable("T_VersionApp", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Identity.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("部门名称");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<long?>("LeaderId")
                        .HasColumnType("bigint")
                        .HasComment("部门负责人id");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("备注");

                    b.HasKey("Id");

                    b.ToTable("T_Department", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Identity.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasComment("年龄");

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("手机号");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasComment("部门id");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<string>("JobName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("岗位名称");

                    b.Property<int>("LoginPermissions")
                        .HasColumnType("int")
                        .HasComment("登录权限 1-无权限 2-web权限  3-app权限 4-小程序权限  5-所有权限");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("密码");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("盐");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("照片地址");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("真实姓名");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("备注");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasComment(" 性别 1-男 2-女");

                    b.Property<long?>("ShiftId")
                        .HasColumnType("bigint")
                        .HasComment("班次id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("员工状态 1-正常 2-离职");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ShiftId");

                    b.ToTable("T_Employee", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Identity.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ButtonName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("按钮名称");

                    b.Property<string>("Component")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("组件");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("描述");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("图标");

                    b.Property<int>("IsButton")
                        .HasColumnType("int")
                        .HasComment("是否是按钮 1-否 2-是");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasComment("层级");

                    b.Property<string>("MenuCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("菜单或按钮编码");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("菜单名称");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("菜单名称");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("父级id");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("路由");

                    b.HasKey("Id");

                    b.ToTable("T_Menu", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Identity.MobilePermissions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("父级id");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("权限项编码");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("权限项名称");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("备注");

                    b.HasKey("Id");

                    b.ToTable("T_MobilePermissions", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Identity.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("id主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasComment("软删  1-未删除 2-已删除");

                    b.Property<string>("MobilePermissions")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("移动端权限项");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("权限项");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("备注");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("角色（职位）名称");

                    b.HasKey("Id");

                    b.ToTable("T_Role", (string)null);
                });

            modelBuilder.Entity("UsersRoles", b =>
                {
                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("T_EmployeeRoleRelation", (string)null);
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Identity.Employee", b =>
                {
                    b.HasOne("Solution.Core.Domain.NpgSqlEntities.Identity.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Solution.Core.Domain.NpgSqlEntities.Common.ShiftInfo", "ShiftInfo")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.Navigation("Department");

                    b.Navigation("ShiftInfo");
                });

            modelBuilder.Entity("UsersRoles", b =>
                {
                    b.HasOne("Solution.Core.Domain.NpgSqlEntities.Identity.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Solution.Core.Domain.NpgSqlEntities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Solution.Core.Domain.NpgSqlEntities.Identity.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
